version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - errname
    - errorlint
    - forcetypeassert
    - gosec
    - loggercheck
    - misspell
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - reassign
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - cmd/docs-gen
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - cmd/docs-gen
      - third_party$
      - builtin$
      - examples$
