version: 2

project_name: redpanda-connect

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/redpanda-connect
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: "386"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Version }}
      - -X main.DateBuilt={{ .Date }}

gomod:
  proxy: true

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

upx:
  - enabled: true
    compress: best
    lzma: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^feat(ci):"
      - "^feat(devbox):"
      - "^feat(docs):"

nfpms:
  - license: Apache-2.0
    maintainer: Artem Klevtsov <a.a.klevtsov@gmail.com>
    homepage: https://github.com/artemklevtsov/redpanda-connect-plugins
    description: Redpanda Connect is a declarative data streaming service
    section: utils
    formats:
      - apk
      - rpm
      - deb
      - archlinux
    provides:
      - benthos
      - redpanda-connect

dockers:
  - image_templates:
      - "ghcr.io/artemklevtsov/{{ .ProjectName }}:{{ .Version }}-arm64"
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=maintainer=Artem Klevtsov <a.a.klevtsov@gmail.com>"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.url=https://github.com/artemklevtsov/redpanda-connect-plugins"
      - "--label=org.opencontainers.image.source=https://github.com/artemklevtsov/redpanda-connect-plugins"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--platform=linux/arm64"
  - image_templates:
      - "ghcr.io/artemklevtsov/{{ .ProjectName }}:{{ .Version }}-amd64"
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=maintainer=Artem Klevtsov <a.a.klevtsov@gmail.com>"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.url=https://github.com/artemklevtsov/redpanda-connect-plugins"
      - "--label=org.opencontainers.image.source=https://github.com/artemklevtsov/redpanda-connect-plugins"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: "ghcr.io/artemklevtsov/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/artemklevtsov/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/artemklevtsov/{{ .ProjectName }}:{{ .Version }}-amd64"
  - name_template: "ghcr.io/artemklevtsov/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/artemklevtsov/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/artemklevtsov/{{ .ProjectName }}:{{ .Version }}-amd64"

release:
  footer: |
    ## Docker images

    To pull the image, you can execute the following command:
    ```
    docker pull ghcr.io/artemklevtsov/{{ .ProjectName }}:{{ .Version }}
    ```
