input:
  generate:
    count: 1
    mapping: |
      #!blobl
      root.text = "example"

pipeline:
  processors:
    - mapping: |
        #!blobl
        root.id_zero = this.text.uuid_v5()
        root.id_dns = this.text.uuid_v5("dns")
        root.id_oid = this.text.uuid_v5("oid")
        root.id_url = this.text.uuid_v5("url")
        root.id_x500 = this.text.uuid_v5("x500")
        root.id_custom = this.text.uuid_v5("a399144d-8527-4554-abcd-7adac6c08d7d")

output:
  stdout: {}
