name: goreleaser

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - name: Cleanup CI runner
        run: |
          sudo rm -rf ${AGENT_TOOLSDIRECTORY}
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/google/chrome
          sudo rm -rf /opt/microsoft/msedge
          sudo rm -rf /opt/microsoft/powershell
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/lib/node_modules
          docker rmi $(docker image ls -aq) || true
          docker image prune --all --force
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Setup qemu
        uses: docker/setup-qemu-action@v3
      - name: Setup builx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
